{
 "title": "Customer Churn Model Evaluation",
 "time": { "from": "2025-07-21T00:22:17.581Z", "to": "2025-07-21T00:52:24.936Z" },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 0 },
   "options": {
    "content": "<div style=\"text-align: center\"><h1>Latest Prediction Scores</h1></div>"
   }
  },
  {
   "title": "F1 Score",
   "type": "stat",
   "gridPos": { "h": 7, "w": 5, "x": 2, "y": 2 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select value \r\nfrom drift_metrics \r\nwhere metric_name = 'f1score'\r\norder by created_at \r\ndesc limit 1"
    }
   ]
  },
  {
   "title": "Precision",
   "type": "stat",
   "gridPos": { "h": 7, "w": 5, "x": 7, "y": 2 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select value \r\nfrom drift_metrics \r\nwhere metric_name = 'precision'\r\norder by created_at \r\ndesc limit 1"
    }
   ]
  },
  {
   "title": "Recall",
   "type": "stat",
   "gridPos": { "h": 7, "w": 5, "x": 12, "y": 2 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select value \r\nfrom drift_metrics \r\nwhere metric_name = 'recall'\r\norder by created_at \r\ndesc limit 1"
    }
   ]
  },
  {
   "title": "Accuracy",
   "type": "stat",
   "gridPos": { "h": 7, "w": 5, "x": 17, "y": 2 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select value \r\nfrom drift_metrics \r\nwhere metric_name = 'accuracy'\r\norder by created_at \r\ndesc limit 1"
    }
   ]
  },
  {
   "title": "F1 Score over time",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 5, "x": 2, "y": 9 },
   "targets": [
    {
     "rawSql": "select created_at, value\r\nfrom drift_metrics \r\nwhere metric_name = 'f1score'\r\norder by created_at"
    }
   ]
  },
  {
   "title": "Precision over time",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 5, "x": 7, "y": 9 },
   "targets": [
    {
     "rawSql": "select created_at, value\r\nfrom drift_metrics \r\nwhere metric_name = 'precision'\r\norder by created_at"
    }
   ]
  },
  {
   "title": "Recall over time",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 5, "x": 12, "y": 9 },
   "targets": [
    {
     "rawSql": "select created_at, value\r\nfrom drift_metrics \r\nwhere metric_name = 'recall'\r\norder by created_at"
    }
   ]
  },
  {
   "title": "Accuracy over time",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 5, "x": 17, "y": 9 },
   "targets": [
    {
     "rawSql": "select created_at, value\r\nfrom drift_metrics \r\nwhere metric_name = 'accuracy'\r\norder by created_at"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 14 },
   "options": {
    "content": "<div style=\"text-align: center\"><h1>Drift Summary Metrics</h1></div>"
   }
  },
  {
   "title": "Number of Drifted Columns",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "rawSql": "select created_at, value\r\nfrom drift_metrics \r\nwhere metric_name = 'driftedcolumnscount[count]'\r\norder by created_at"
    }
   ]
  },
  {
   "title": "Drifted Column Share of Total Columns",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "rawSql": "select created_at, value\r\nfrom drift_metrics \r\nwhere metric_name = 'driftedcolumnscount[share]'\r\norder by created_at"
    }
   ]
  },
  { "type": "text", "gridPos": { "h": 2, "w": 24, "x": 0, "y": 24 }, "options": { "content": "## Metric Drift p-Values" } },
  {
   "title": "Churn",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 26 },
   "targets": [
    {
     "rawSql": "select created_at, value as \"p-value\"\r\nfrom drift_metrics \r\nwhere metric_name = 'valuedrift_churn'\r\norder by created_at"
    }
   ]
  },
  {
   "title": "Age Group",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 26 },
   "targets": [
    {
     "rawSql": "select created_at, value as \"p-value\"\r\nfrom drift_metrics \r\nwhere metric_name = 'valuedrift_age_group'\r\norder by created_at"
    }
   ]
  },
  {
   "title": "Call Failures",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 26 },
   "targets": [
    {
     "rawSql": "select created_at, value as \"p-value\"\r\nfrom drift_metrics \r\nwhere metric_name = 'valuedrift_call_failure'\r\norder by created_at"
    }
   ]
  },
  {
   "title": "Charge Amount",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 32 },
   "targets": [
    {
     "rawSql": "select created_at, value as \"p-value\"\r\nfrom drift_metrics \r\nwhere metric_name = 'valuedrift_charge_amount'\r\norder by created_at"
    }
   ]
  },
  {
   "title": "Complains",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 32 },
   "targets": [
    {
     "rawSql": "select created_at, value as \"p-value\"\r\nfrom drift_metrics \r\nwhere metric_name = 'valuedrift_complains'\r\norder by created_at"
    }
   ]
  },
  {
   "title": "Customer Value",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 32 },
   "targets": [
    {
     "rawSql": "select created_at, value as \"p-value\"\r\nfrom drift_metrics \r\nwhere metric_name = 'valuedrift_customer_value'\r\norder by created_at"
    }
   ]
  },
  {
   "title": "Distinct Called Numbers",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 38 },
   "targets": [
    {
     "rawSql": "select created_at, value as \"p-value\"\r\nfrom drift_metrics \r\nwhere metric_name = 'valuedrift_distinct_called_numbers'\r\norder by created_at"
    }
   ]
  },
  {
   "title": "Frequency of SMS",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 38 },
   "targets": [
    {
     "rawSql": "select created_at, value as \"p-value\"\r\nfrom drift_metrics \r\nwhere metric_name = 'valuedrift_frequency_of_sms'\r\norder by created_at"
    }
   ]
  },
  {
   "title": "Frequency of Use",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 38 },
   "targets": [
    {
     "rawSql": "select created_at, value as \"p-value\"\r\nfrom drift_metrics \r\nwhere metric_name = 'valuedrift_frequency_of_use'\r\norder by created_at"
    }
   ]
  },
  {
   "title": "Seconds of Use",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 44 },
   "targets": [
    {
     "rawSql": "select created_at, value as \"p-value\"\r\nfrom drift_metrics \r\nwhere metric_name = 'valuedrift_seconds_of_use'\r\norder by created_at"
    }
   ]
  },
  {
   "title": "Status",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 44 },
   "targets": [
    {
     "rawSql": "select created_at, value as \"p-value\"\r\nfrom drift_metrics \r\nwhere metric_name = 'valuedrift_status'\r\norder by created_at"
    }
   ]
  },
  {
   "title": "Subscription Length",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 44 },
   "targets": [
    {
     "rawSql": "select created_at, value as \"p-value\"\r\nfrom drift_metrics \r\nwhere metric_name = 'valuedrift_subscription_length'\r\norder by created_at"
    }
   ]
  }
 ]
}